<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="index.html">Hi-Tech</a>
    </div>
    <!-- Top Menu Items -->
    <ul class="nav navbar-right top-nav">
        
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> John Smith <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li>
                    <a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-fw fa-envelope"></i> Inbox</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-fw fa-gear"></i> Settings</a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
                </li>
            </ul>
        </li>
    </ul>
    <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav side-nav">
            <li>
                <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index'), null, false); ?>"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
            </li>
            <li>
                <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'index'), null, false); ?>"><i class="fa fa-fw fa-users"></i> Utilisateurs</a>
            </li>
            <li>
                <a href="<?php echo $this->url(array('controller' => 'product', 'action' => 'index'), null, false); ?>"><i class="fa fa-fw fa-cubes"></i> Produits</a>
            </li>
            <li>
                    <a href="javascript:;" data-toggle="collapse" data-target="#demo"><i class="fa fa-fw fa-database"></i> Arborescense <i class="fa fa-fw fa-caret-down"></i></a>
                    <ul id="demo" class="collapse">
                        <li class="col-md-12 row">
                            <a href="<?php echo $this->url(array('controller' => 'category', 'action' => 'index'), null, false); ?>" class="col-md-12"></i> Categories</a>
                        </li>
                        <li class="col-md-12 row">
                            <a href="<?php echo $this->url(array('controller' => 'subcategory', 'action' => 'index'), null, false); ?>" class="col-md-12"></i> Sous-Categories</a>
                        </li>
                    </ul>
            </li>
            <li>
                <a href="<?php echo $this->url(array('controller' => 'event', 'action' => 'index'), null, false); ?>"><i class="fa fa-fw fa-calendar"></i> Sessions de vente</a>
            </li>
            <li>
                <a href="<?php echo $this->url(array('controller' => 'cart', 'action' => 'index'), null, false); ?>"><i class="fa fa-fw fa-shopping-cart"></i> Paiements</a>
            </li>
            <li>
                <a href="<?php echo $this->url(array('controller' => 'credential', 'action' => 'index'), null, false); ?>"><i class="fa fa-fw fa-edit"></i> Roles & Droits</a>
            </li>
        </ul>
    </div>
</nav>