<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <link href="assets/css/bootstrap.min.css" rel="stylesheet">
    <link href="assets/css/sb-admin.css" rel="stylesheet">
    <link href="assets/css/plugins/morris.css" rel="stylesheet">
    <link href="assets/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <script src="assets/js/jquery.js"></script>
    <script src="assets/js/bootstrap.min.js"></script>
    <script src="assets/js/plugins/morris/raphael.min.js"></script>
    <script src="assets/js/plugins/morris/morris.min.js"></script>
    <script src="assets/js/plugins/morris/morris-data.js"></script>
    <script src="assets/js/jquery-2.1.3.min.js"></script>
    <title></title>
</head>
<body>
	<div class="wrapper"
		<header>
			<?php
				include ('header.phtml');
			?>
		</header>
		<div class="page-wrapper">
			<div class="container-fluid">
				PLEIN DE TRUC! TOUT PLEIN! ET ENCORE PLUS!
			</div>
	    </div>
	</div>
</body>
</html>
