<?php

//Base de données
define('DB_NAME_HITECH', 'hitech');

//Tables
define('DB_TABLE_CATEGORY', DB_NAME_HITECH . '.categories');
define('DB_TABLE_USER', DB_NAME_HITECH . '.utilisateurs');
define('DB_TABLE_EVENT', DB_NAME_HITECH . '.evenements');
define('DB_TABLE_CART', DB_NAME_HITECH . '.paniers');
define('DB_TABLE_PRODUCT', DB_NAME_HITECH . '.produits');
define('DB_TABLE_SUB_CATEGORY', DB_NAME_HITECH . '.sous-categories');

